### ISSUE TITLE
AHK does not support capitalization

### ISSUE THREAD

**Issue by yovliporat** [levavft/AHKLatex#1]
So delta is the same as Delta, resulting in delta being swapped for ∆ and the like

**Comment by levavft** [comment]
Relevant links that might help me solve this:
https://www.autohotkey.com/boards/viewtopic.php?t=31167
https://www.autohotkey.com/docs/commands/StringCaseSense.htm
https://autohotkey.com/board/topic/53843-case-sensitive-hotkeys/
https://autohotkey.com/board/topic/88762-making-a-script-case-sensitive/
The last one seems the most promising (& simple)

**Comment by levavft** [comment]
Fixed by adding "#Hotstring c" at the start.
