### ISSUE TITLE
Delta and delta delete characters before them when adding another space

### ISSUE THREAD

**Issue by yovliporat** [levavft/AHKLatex#6]
When I type slash delta or slash Delta and add another space afterward, 4 characters are deleted before the 𝛿.
In addition, when this happens with 𝛿 it turns into ∆.

**Comment by levavft** [comment]
I couldn't reproduce the issue. Try making sure all previous runs of the scripts have been killed. (since the script has been renamed a few times, there might be some residues).

**Comment by yovliporat** [comment]
Killed all the AutoHotKey processes and started it back up, seemed to work.
