### ISSUE TITLE
A previous repo with similar goals exists, see what we can learn / get from there.

### ISSUE THREAD

**Issue by levavft** [levavft/AHKLatex#8]
https://gist.github.com/kbauer/e8fee6514d124d5961f51fd7ba571bfd

It seems to be an autogenerated file. It seems to have every Unicode character, and multiple shortcuts for most of those.
But, it seems to have lots of unneeded information and code (everything there is made to handle emacs), and it doesn't use *,o,? to make the codes smoother.

If we'll want to integrate this, the best way would probably to create a convertor from that file style to our file style (since this is literally almost 30k lines of code).

**Comment by 3strategy** [comment]
This piece of code is just scary. not clear what the purpose is. hard to read the shortcuts. 
I'd always take a code that is 100 times smaller that does 99% of the work (besides it will do what we thing is useful, not just every single unicode that was invented).
It's always worth checking out the competitions though. Need to take some time and run it to see if there are any superior capabilities to inherit.

**Comment by levavft** [comment]
From rereading - 

Only interesting parts of the code are at lines 28-58, and looking at a single example of a hotstring - line 1588+.

Lines 28-58: Header lines, differences from ours:
1. Another methodology for choosing on which apps it will be used. Ours seems better.
2. Their global hotstring directive: C,O,?. We use: C, and specify ?,O,* in a more nuanced manner.
3. They have a hotstring endchar directive: `n (newline), `t (tab). We use the default `s (space). It seems reasonable to add these as well.

Lines 1588+:
1. We group hotstrings based on our global variables, e.g. \pi could appear multiple times in the file if it makes sense, but if's and function uses are kept to a minimum. They group by hotstring, so each hostring has to recheck all the different options.
Their methodology seems more reasonable for computer generated code (which it is) and ours for human generated code (which it is), no change required.
2. They have all possible tex symbols and all common shortcuts. I think its just cumbersome to work like that. If anyone needs a specific symbol that hasn't been added, they can request it here and I'll add it together with anything that should come with it.
That being said, It might be cool to create a convertor from our file & their file into a non-human readable file that gets the best of both worlds. And work on the convertor only in the future. I will do this if its requested.

**Comment by levavft** [comment]
After another read of AHK's hotstrings, I was wrong about the default hotstring end characters. 
They are: -()[]{}:;'"/\,.?!`n `t
This doesn't seem to conflict with any of our hotstrings, so I see no reason to restrict them.
At this point, beyond creating a script that would get all the hotstrings from their file and convert them to our format, I don't see anything else that could be gained. This doesn't look particularly useful either. So I'm closing this issue for now.
